# PRAKTIKUM - 2 AS2112 Astronomi Komputasi

## Solusi Numerik Sistem Persamaan Linear


***Selasa, 29 September 2020***

09:00 - 23:59 WIB

Tasya Nadzmus Soraya

NIM: 10319035

---


### Catatan pengingat tentang python: indeks, array, matriks, modul, objek

1. Python menghitung indeks (*counter*) mulai dari nol. Indeks baris dan kolom matriks dimulai dari 0, kemudian 1, 2, ...dst
2. Modul python antara lain berisi data/konstanta khas, atau fungsi. Seringkali modul python digunakan karena kebutuhan akan pemakaian fungsi-fungsi di dalamnya. Dengan mengambil contoh modul sembarang (*non existence*) **`foo`** yang akan digunakan, cara (menyiapkan untuk) memanggil fungsi sembarang (*non existence*) **`func1`** dan **`func2`** dapat menggunakan beberapa alternatif:

   a. (Daftar) **nama fungsi** diimpor dengan cara **dituliskan**. Misal
      ```python
      from foo import func1,func2
      ```
      
   b. **Seluruh isi modul diimpor** (meskipun tidak seluruh fungsi digunakan)
      ```python
      from foo import *
      ```

   c. **Modul diimpor sebagai objek**
      ```python
      import foo
      ```

   d. **Modul diimpor sebagai objek dengan memberi nama lain**
      ```python
      import foo as fo
      ```
   Bagi yang ingin mengandalkan paradigma OOP (*Object Oriented Programming*), pilihan ketiga atau keempat sebaiknya digunakan.
3. Dalam praktikum ini, konstruksi dan operasi matriks akan dimanfaatkan. Berikut ini beberapa blok contoh kode deklarasi/konstruksi matriks via modul **`numpy`** dengan pendekatan objek:
   ```python
   import numpy             # ATAU: import numpy as np

   # MATRIKS 1 KOLOM
   C = numpy.array([25., -3., 21.])

   # MATRIKS PERSEGI 2x2
   A  = numpy.array([
                    [ 4., -3.],
                    [ 3.,  1.]
                    ])

   # MATRIKS PERSEGI 2x2 sebagai GABUNGAN 2 ARRAY
   row0 = [ 4, -2]
   row1 = [ 1, -3]
   B    = numpy.array([
                       row0, 
                       row1
                      ])

   # KONSEKUENSI DARI CARA MENGGUNAKAN INDEKS DI PYTHON
   c1   = C[1]    # yaitu -3
   a00  = A[0][0] # yaitu  4
   b10  = B[1][0] # yaitu  1
   ```

4. Dan berikut ini beberapa blok contoh kode deklarasi/konstruksi matriks via modul **`numpy`** tanpa pendekatan objek:
   ```python
   from numpy import array  # ATAU: from numpy import *

   # MATRIKS 1 KOLOM
   C = array([25., -3., 21.])

   # MATRIKS PERSEGI 2x2
   A  = array([
              [ 4., -3.],
              [ 3.,  1.]
              ])

   # MATRIKS PERSEGI 2x2 sebagai GABUNGAN 2 ARRAY
   row0 = [ 4, -2]
   row1 = [ 1, -3]
   B    = array([
                 row0, 
                 row1
                ])

   # ... dst ...
   ```
5. Modul python yang banyak digunakan dan mempermudah pendefinisian *array* dan matriks adalah **`numpy`**
6. Bersama dengan modul **`scipy`**, penanganan matriks lebih lengkap tertangani dengan menggunakan submodul **`scipy.linalg`** yang berisi sejumlah operasi matriks untuk SPL:

   * perkalian matriks (`dot`)        : **`numpy.dot`**
   * cek identik tidaknya dua matriks : **`numpy.allclose`**
   * determinan matriks (`det`)       : **`scipy.linalg.det`**
   * invers matriks (`inv`)           : **`scipy.linalg.inv`**
   * lower/upper triangular matrix    : **`scipy.linalg.tril`**, **`scipy.linalg.triu`**

     ... bahkan

   * solusi SPL                       : **`scipy.linalg.solve`**

   Silakan merujuk ke [dokumentasi Numpy dan Scipy](https://docs.scipy.org/doc/) **atau cek dokumentasi per fungsi di python *prompt* (atau di Jupyter Notebook)** mengikuti contoh berikut ini (untuk modul `numpy`):

---

```bash
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> dir(numpy)
... ['ALLOW_THREADS', ...

  ...'array',

      'zeros_like']
>>> help(numpy.array)
    ...

```

---


### Mencari solusi numerik SPL: eliminasi Gauss

SPL dalam bentuk persamaan matriks

$$
\mathbf{A}\;\mathbf{X} = \mathbf{C}
$$

dapat diselesaikan dengan terlebih dulu melakukan konstruksi matriks $\mathbf{A}$ dan $\mathbf{C}$, dan kemudian langkah inti mencari solusi numerik SPL tersebut adalah cukup dengan fungsi **`solve`** yang disediakan submodule **`scipy.linalg`**, misalkan

```python
X = scipy.linalg.solve(A, C)
```

atau

```python
X = solve(A, C)
```

tergantung pada cara memanggil `scipy.linalg`.


### Mencari solusi numerik SPL: Gauss-Seidel (dengan memanfaatkan matriks triangulasi L dan U)

*Dengan tidak mengaitkan asal-usul matriks $\mathbf{A}$ dengan prosedur dekomposisi LU (yang sudah dipelajari di kuliah sebagai: $\mathbf{A} = \mathbf{L}\;\mathbf{U}$)*, matriks $\mathbf{A}$ secara ringkas dapat dipandang sebagai kombinasi penjumlahan matriks triangulasi bawah $\mathbf{L}$ dan matriks triangulasi atas $\mathbf{U}$:

$$
\mathbf{A} = \mathbf{L} + \mathbf{U}
$$

sehingga

$$
\mathbf{A}\;\mathbf{X} = (\mathbf{L} + \mathbf{U})\;\mathbf{X} = \mathbf{C}
$$

atau

$$
\mathbf{L}\;\mathbf{X} = \mathbf{C} - \mathbf{U}\;\mathbf{X}
$$

atau

$$
\mathbf{X} = \mathbf{L}^{-1}\left(\mathbf{C} - \mathbf{U}\;\mathbf{X}\right)
$$

Dengan pendekatan iteratif, update entry matriks $\mathbf{X}$ di ruas kiri diperoleh dengan memasukkan entry $\mathbf{X}$ dari iterasi sebelumnya:

$$
\mathbf{X}_{(i+1)} = \mathbf{L}^{-1}\left(\mathbf{C} - \mathbf{U}\;\mathbf{X}_i\right)
$$

---

*Buatlah salinan/backup dari file ini. File .ipynb yang Anda terima ini **dapat digunakan sebagai template file laporan praktikum** yang dapat Anda sunting sesuai dengan kebutuhan praktikum. Jika karena suatu hal Anda tidak menggunakan Jupyter Notebook, gunakan piranti lunak lain, misal **Spyder**, **CodeBlocks**, **Visual Studio Code**, atau editor sederhana sekalipun untuk mengerjakan dan menyiapkan file laporan. Jika skenario kedua ini Anda gunakan, salinlah keluaran dari program python ini dan tambahkan di ujung file, lalu kirimkan file tersebut.*

***Seperti praktikum sebelumnya, file laporan ini diuji mandiri di Google Colab dan share ke muhamadirfanhakim@gmail.com, dan setelah tuntas diunggah kembali ke MS Teams di fasilitas assignment.***

---

### Tugas 1

*Gunakan metode eliminasi Gauss dengan memanfaatkan fungsi **solve** untuk mencari solusi SPL dari augmented matrix berikut ini:*


$$
\left[
\begin{array}{rrrrrrrrrrrrrrr|r}
0&0&1&0&0&0&0&0&0&0&0&0&0&0&0&0\\
100&10&1&0&0&0&0&0&0&0&0&0&0&0&0&227,\!04\\
0&0&0&100&10&1&0&0&0&0&0&0&0&0&0&227,\!04\\
0&0&0&225&15&1&0&0&0&0&0&0&0&0&0&362,\!78\\
0&0&0&0&0&0&225&15&1&0&0&0&0&0&0&362,\!78\\
0&0&0&0&0&0&400&20&1&0&0&0&0&0&0&517,\!35\\
0&0&0&0&0&0&0&0&0&400&20&1&0&0&0&517,\!35\\
0&0&0&0&0&0&0&0&0&506,\!25&22,\!5&1&0&0&0&602,\!97\\
0&0&0&0&0&0&0&0&0&0&0&0&506,\!25&22,\!5&1&602,\!97\\
0&0&0&0&0&0&0&0&0&0&0&0&900&30&1&901,\!67\\
20&1&0&-20&-1&0&0&0&0&0&0&0&0&0&0&0\\
0&0&0&30&1&0&-30&-1&0&0&0&0&0&0&0&0\\
0&0&0&0&0&0&40&1&0&-40&-1&0&0&0&0&0\\
0&0&0&0&0&0&0&0&0&45&1&0&-45&-1&0&0\\
1&0&0&0&0&0&0&0&0&0&0&0&0&0&0&0\\
\end{array}
\right]
$$

### Tugas 2


*Berikut ini adalah konstruksi dasar metode **Gauss-Seidel** untuk pendekatan iteratif:*
   ```python
   # GAUSS-SEIDEL menggunakan matriks L dan U: A = L + U; Ax = C; n = ukuran SPL
   def gseidel(A, C, x, n):

       # cari L dengan fungsi `tril` dari submodul `scipy.linalg`
       L = 

       # cari U tidak perlu dengan fungsi `triu`
       U = A - L

       for i in range(n):

           # panggil fungsi `dot` dan `inv` untuk menghitung matriks x (lihat formulasi)
           x = dot(inv(L), C - dot(U, x))

           # tampilkan hasil perhitungan di setiap iterasi
           print(f'........')

       return
   ```
   *Tanpa memasukkan perhitungan galat bagi perhitungan tiap entry matriks, gunakanlah konstruksi dasar tersebut untuk solusi iteratif SPL dengan augmented matrix berdominasi diagonal berikut ini:*
   $$
   \left[
   \begin{array}{rrr|r}
    4 & -2 &  1 & 1\\
    1 & -3 &  2 & 2\\
   -1 &  2 &  6 & 3\\
   \end{array}
   \right]
   $$

### Kode Kehormatan

1. Saintis sekalipun mungkin salah, tetapi tidak boleh dan tidak berguna berdusta. Begitupun juga pembelajar sains, karena dusta diintai musuh besarnya, yaitu lupa.
2. Kerjakanlah tugas dengan dua serangkai semangat yang serasi: kemandirian dan kejujuran akademik.
3. Pengawasan (*proctoring*) secara daring (*online*) adalah upaya teknis yang belum tentu tepat, namun yang hakiki adalah keinsyafan hati.
4. Seluruh isi file ini saya hibahkan dengan klausul [copyleft](https://en.wikipedia.org/wiki/Copyleft). Setelah berada di tangan Anda, Anda bebas untuk mengakui kepemilikan dan bebas untuk melakukan suntingan. (Lihat pula modul praktikum sebelumnya). 

In [ ]:
import numpy
import scipy.linalg

In [ ]:
#---------------------------------#
#             TUGAS 1             #
#---------------------------------#

import numpy
import scipy.linalg

# (1) KONSTRUKSI MATRIKS A dan C dari augmented matrix

#Matriks A 
row0 = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
row1 = [100, 10, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
row2 = [0, 0, 0, 100, 10, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
row3 = [0, 0, 0, 225, 15, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
row4 = [0, 0, 0, 0, 0, 0, 225, 15, 1, 0, 0, 0, 0, 0, 0]
row5 = [0, 0, 0, 0, 0, 0, 400, 20, 1, 0, 0, 0, 0, 0, 0]
row6 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 400, 20, 1, 0, 0, 0]
row7 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 506.25, 22.5, 1, 0, 0, 0]
row8 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 506.25, 22.5, 1]
row9 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 900, 30, 1]
row10 = [20, 1, 0, -20, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
row11 = [0, 0, 0, 30, 1, 0, -30, -1, 0, 0, 0, 0, 0, 0, 0]
row12 = [0, 0, 0, 0, 0, 0, 40, 1, 0, -40, -1, 0, 0, 0, 0]
row13 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 45, 1, 0, -45, -1, 0]
row14 = [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

A = numpy.array([
                  row0,
                  row1,
                  row2,
                  row3,
                  row4,
                  row5,
                  row6,
                  row7,
                  row8,
                  row9,
                  row10,
                  row11,
                  row12,
                  row13,
                  row14
                ])

#Matriks C
C = numpy.array([
                 0,
                 227.04,                 
                 227.04,
                 362.78,
                 362.78,
                 517.35,
                 517.35,
                 602.97,
                 602.97,
                 901.67,
                 0,
                 0,
                 0,
                 0,
                 0
                ])

# (2) SOLVE
X = scipy.linalg.solve(A, C)
print(X)

In [64]:
#---------------------------------#
#             TUGAS 2             #
#---------------------------------#

# (0) DEFINISIKAN ALGORITMA GAUSS-SEIDEL untuk dua matriks yang diberikan beserta ukuran SPL (lihat bahasan ide dasar)

def gseidel(A, C, x, n):

       # cari L dengan fungsi `tril` dari submodul `scipy.linalg`
       L = scipy.linalg.tril(A)

       # cari U tidak perlu dengan fungsi `triu`
       U = A - L

       for i in range(n):

           # panggil fungsi `dot` dan `inv` untuk menghitung matriks x (lihat formulasi)
           x = numpy.dot(scipy.linalg.inv(L), C - numpy.dot(U, x))

           # tampilkan hasil perhitungan di setiap iterasi
           print("saat iterasi ke-",i+1,"nilai x adalah")
           print(x)
       return 

# (1) KONSTRUKSI MATRIKS A dan C dari augmented matrix

A = numpy.array([
                [4.,-2.,1.],
                [1.,-3.,2.],
                [-1.,2.,6.]
                ])

C = numpy.array([
                [1],
                [2],
                [3]
                ])

x = numpy.array([
                 [1],
                 [1],
                 [1]
                ])
# (2) PANGGIL ALGORITMA GAUSS-SEIDEL sekaligus untuk menampilkan solusi hampiran numerik
n = 10
gseidel(A, C, x, n)

saat iterasi ke- 1 nilai x adalah
[[0.5       ]
 [0.16666667]
 [0.52777778]]
saat iterasi ke- 2 nilai x adalah
[[ 0.20138889]
 [-0.24768519]
 [ 0.61612654]]
saat iterasi ke- 3 nilai x adalah
[[-0.02787423]
 [-0.26520705]
 [ 0.58375664]]
saat iterasi ke- 4 nilai x adalah
[[-0.02854268]
 [-0.2870098 ]
 [ 0.59091282]]
saat iterasi ke- 5 nilai x adalah
[[-0.0412331 ]
 [-0.28646916]
 [ 0.58861753]]
saat iterasi ke- 6 nilai x adalah
[[-0.04038896]
 [-0.28771796]
 [ 0.58917449]]
saat iterasi ke- 7 nilai x adalah
[[-0.04115261]
 [-0.28760121]
 [ 0.5890083 ]]
saat iterasi ke- 8 nilai x adalah
[[-0.04105268]
 [-0.28767869]
 [ 0.58905078]]
saat iterasi ke- 9 nilai x adalah
[[-0.04110204]
 [-0.28766682]
 [ 0.5890386 ]]
saat iterasi ke- 10 nilai x adalah
[[-0.04109306]
 [-0.28767195]
 [ 0.58904181]]
